services:
  backend:
    build: ./backend
    container_name: mini-backend
    environment:
      - PORT=3006
      - NODE_ENV=production
    ports:
      - "3006:3006"

  web:
    build: .
    container_name: mini-web
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:3006
    depends_on:
      - backend
    ports:
      - "3000:3000"
