services:
  backend:
    build: ./backend
    environment:
      - PORT=3006
      - NODE_ENV=production
    ports:
      - "${BACKEND_PORT:-3006}:3006"
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:3006/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build: .
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:3006
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "${WEB_PORT:-3000}:3000"
